### PR TITLE
AR-145 UI overhaul input page

### PR DESCRIPTION
**Pull request by ruudkas**
Changes for [this](https://academic-cs458.atlassian.net/jira/software/projects/AR/boards/1?selectedIssue=AR-145) US.

Complete overhaul of all components for the input page. The information from the database is all being pulled from the service and selected values are updated to the user service. Unit tests have been written for all of the dropdowns and buttons with the exception of the menu and login buttons which will be implemented in a later story.

### CODE REVIEW

**Comment by ChrisVasterling** [comment]
When dragging a course, it is always dragging the first course in the first category. The screenshot is from psychology, but it was also complaining about CS145 for the CS concentrations (which happens to be at the top of the list for all cs concentrations) 

Input page looks good though

image

**Comment by ruudkas** [comment]
> When dragging a course, it is always dragging the first course in the first category. The screenshot is from psychology, but it was also complaining about CS145 for the CS concentrations (which happens to be at the top of the list for all cs concentrations)
> 
> Input page looks good though
> 
> image

Can you explain this more? I'm attempting to recreate this and I'm not seeing this issue.

**Comment by ruudkas** [comment]
> When dragging a course, it is always dragging the first course in the first category. The screenshot is from psychology, but it was also complaining about CS145 for the CS concentrations (which happens to be at the top of the list for all cs concentrations)
> 
> Input page looks good though
> 
> image

This is actually an interesting bug caused by the fact that it is matching courses based on id and not name. Since the course list is currently returning courses that all have undefined ids it seems to be grabbing the first course in the list. Although it looks like their are now ids under a new variable name, so I will see if I can update it.

**Comment by ruudkas** [comment]
> > When dragging a course, it is always dragging the first course in the first category. The screenshot is from psychology, but it was also complaining about CS145 for the CS concentrations (which happens to be at the top of the list for all cs concentrations)
> > Input page looks good though
> > image
> 
> This is actually an interesting bug caused by the fact that it is matching courses based on id and not name. Since the course list is currently returning courses that all have undefined ids it seems to be grabbing the first course in the list. Although it looks like their are now ids under a new variable name, so I will see if I can update it.

The changes to fix this error have been pushed. There is currently a different issue where testing works with v15 of react-dnd and the app works with v16 of react-dnd. Using v16 the app is functional for dragging a course and getting the proper warnings.

**Review by ChrisVasterling — APPROVED** [review]
Testing seem to work on Matthews laptop, but does not work on mine or kassidy's.

**Review by Raffeln6264 — APPROVED** [review]
A little sus ngl but I can approve it

**Pull request merged**
