### PR TITLE
Ar 96 suggested courses

### PR DESCRIPTION
**Pull request by ChrisVasterling**
# Jira Ticket

Jira ticket number with link: [Ar-96](https://academic-cs458.atlassian.net/jira/software/projects/AR/boards/1/backlog?selectedIssue=AR-96)

# Description of Changes
_Please describe what this pull request should accomplish_
Use the four year plan to suggest courses to the users

# Type of Change

- [ ] Bug Fix
- [ ] New Feature
- [X] Feature Update

# How has this been tested?
_Please describe the tests that you used to verify your changes._
Automated testing `SemesterList.test.tsx`

**Manual Tests**
_Please explain why they are not automated._ 
N/A

# Checklist
- [x] My code follows ES Lint guidelines
- [X] My solution meets all of the acceptance criteria for the user story
- [X] My code contains necessary comments and documentation
- [X] I have added tests that are useful and cover the new changes
- [X] New and existing unit tests pass locally

### CODE REVIEW

**Comment by ruudkas** [comment]
I have a couple comments/requests:

- Can suggested content be suggested courses instead? We call them courses everywhere else.
- Can we have the suggested gen eds be buttons that open the category in the course list? Looking at this one, they have multiple categories under most gen eds, but if we could manually interject the name of the suggested gen ed i.e. ARHU into the searchable dropdown it would display the categories to the user. (I don't know if this is easily done but the current display is a bit ambiguous)
- Additionally I'm not a fan of putting the gen ed in the "header" portion (I assume this is because anything in the other part is in a course list element), in which case could we potentially "fake" it being in the body by changing the background color?
- Not sure how I feel about the user being able to drag a suggested course to any semester, but it's not technically a problem, so I'll let it go.
- The styling change to fix the course dropdowns to be left aligned has been lost 😢

**Comment by ChrisVasterling** [comment]
> I have a couple comments/requests:
> 
> * Can suggested content be suggested courses instead? We call them courses everywhere else.
> * Can we have the suggested gen eds be buttons that open the category in the course list? Looking at this one, they have multiple categories under most gen eds, but if we could manually interject the name of the suggested gen ed i.e. ARHU into the searchable dropdown it would display the categories to the user. (I don't know if this is easily done but the current display is a bit ambiguous)
> * Additionally I'm not a fan of putting the gen ed in the "header" portion (I assume this is because anything in the other part is in a course list element), in which case could we potentially "fake" it being in the body by changing the background color?
> * Not sure how I feel about the user being able to drag a suggested course to any semester, but it's not technically a problem, so I'll let it go.
> * The styling change to fix the course dropdowns to be left aligned has been lost 😢

- I can do the rename. The reason why I changed it from "courses" was because of the gen-ed requirements (not everything suggested was a course)
- I would also like to make the gen-eds be buttons but I don't it would work well since the user would still need to open the dropdown and select the proper category. Would a label like "Categories" in the suggestion box help?
- I can try "faking" the background color of the gen-ed area to see how it looks
- I don't think restricting which semester a suggested course can be dragged to would be helpful since a user may plan their junior year as a whole and want to bring a suggested spring course into the fall rather than manually selecting it from the primary course list
- Honestly, don't know why this happened 🙃. I can try re-merging in main or manually add the change

**Review by ruudkas — APPROVED** [review]
I will approve it, but I have one last request.

Can we adjust the gen ed courses to be in line with the major courses. The left margin difference is a little wonky.
image

**Review by Raffeln6264 — APPROVED** [review]
LGTM! Didn't notice anything major.

**Pull request merged**
