### PR TITLE
Ar-154 academic service (actually api) testing

### PR DESCRIPTION
**Pull request by ChrisVasterling**
# Jira Ticket

Jira ticket number with link: [AR-154](https://academic-cs458.atlassian.net/jira/software/projects/AR/boards/1/backlog?selectedIssue=AR-151)

# Description of Changes
I added API testing to our existing endpoints for:
- `/api/courses`
- `/api/requiremetns`
- `/api/subjects`

# Type of Change

- [ ] Bug Fix
- [ ] New Feature
- [ ] Feature Update
- [x] Added testing

# How has this been tested?
We are using automated testing to test the API endpoints

**Automated Tests (Preferred)**
- [x] All tests in the /\_\_test\_\_/api folder

Currently, one of the tests fail (for `/api/courses/gened`) because a value in the `semesters` column of the course table (ANTH-230) is an empty string rather than null. This value likely needs to be changed to null. 

**Manual Tests**
N/A

# Checklist
- [x] My code follows ES Lint guidelines
- [x] My solution meets all of the acceptance criteria for the user story
- [x] My code contains necessary comments and documentation
- [x] I have added tests that are useful and cover the new changes
- [x] New and existing unit tests pass locally

### CODE REVIEW

**Review by ruudkas — APPROVED** [review]
Looks good to me. I'm not a fan of how many files we're adding but they are named clear enough that I think it's fine. 

I can fix the string to be null on my branch with my other db changes.

I would like to see that ES Lint is passing, which I can't because it fails after the tests and never checks linting.

**Comment by ChrisVasterling** [comment]
> I would like to see that ES Lint is passing, which I can't because it fails after the tests and never checks linting.

I could temporarily make the change to the DB in my branch so we see the tests pass, but change it back before merging.

**Comment by ruudkas** [comment]
> > I would like to see that ES Lint is passing, which I can't because it fails after the tests and never checks linting.
> 
> I could temporarily make the change to the DB in my branch so we see the tests pass, but change it back before merging.

Can you try updating the workflow file (under .github/workflows) to contain this line?
image
This should force the lint step to run even if the tests fail. It should still report the test check as a fail, but allow us to see if linting passes or fails as well.

**Comment by ChrisVasterling** [comment]
Linting appears to be working now:
image

**Comment by ruudkas** [comment]
I discovered in creating a PR with code pulled from this branch that it contains an issue that prevents it from building. 
image
It seems to be related to the new expect import on the first line of the __test__/util.tsx file.
It appears that if you just delete expect from the first line it fixes the issue with building and doesn't break anything.

**Review by Raffeln6264 — APPROVED** [review]
This is it chief, looks very nice

**Pull request merged**
