### PR TITLE
Ar 204 change some errors to warnings

### PR DESCRIPTION
**Pull request by ChrisVasterling**
# Jira Ticket

Jira ticket number with link: [AR-204](https://academic-cs458.atlassian.net/jira/software/projects/AR/boards/1/backlog?selectedIssue=AR-204)

# Description of Changes
_Please describe what this pull request should accomplish_
We are not displaying duplicate courses/seasonal snackbar errors as warnings. Prereq errors are still errors. The Error notification was also updated to remove duplicate errors/warnings and display a colored icon

# Type of Change

- [ ] Bug Fix
- [ ] New Feature
- [X] Feature Update

# How has this been tested?
_Please describe the tests that you used to verify your changes._
Testing was already covered but has been updated where needed

**Manual Tests**
_Please explain why they are not automated._
N/A

# Checklist
- [X] My code follows ES Lint guidelines
- [X] My solution meets all of the acceptance criteria for the user story
- [X] My code contains necessary comments and documentation
- [X] I have added tests that are useful and cover the new changes
- [X] New and existing unit tests pass locally

### CODE REVIEW

**Review by the10thWiz — APPROVED** [review]
Looks good, make sure CI passes

**Comment by ChrisVasterling** [comment]
I'm running into an issue where there appears to be a snapshot failing for a DefaultLayout test, but when I attempts to update snapshots, the tests pass locally and there are no changes to the snapshots. I tried deleting the snapshot file in question and re-running the tests with `npm run test -- -u`, one test fails because it can't find "Logout" on the page. However, when I rerun the exact command, all the tests pass locally. 
image

**Comment by ruudkas** [comment]
Two comments:

-  The issue with the snapshot is that you need to pull from main (if you pull from main the test fails locally). We ran into this same issue with Matthew's PR last week.
- I noticed that if I put on some errors then move another course around I keep getting error messages that aren't new. For example, add the prereq errors shown then move around CNIT-133 and you can get CS-244 error message a bunch of times.
image

**Comment by ChrisVasterling** [comment]
- When I pull from main, it says I'm already up to date
- This behavior exists on main as well. Further, I noticed sometimes the message would say that 244 requires 144 and 145, other times it would say 244 requires 145. The only course I was moving was cnit133

**Review by Raffeln6264 — APPROVED** [review]
Make sure the among us aint attacking, then you can merge

**Pull request merged**
