### PR TITLE
Ar 132 create schedule selection from database account page

### PR DESCRIPTION
**Pull request by the10thWiz**
# Jira Ticket

Jira ticket number with link:

# Description of Changes
Adding testing (and fixing any identified bugs) in the accounts page & schedule loading

# Type of Change

- [x] Bug Fix

# How has this been tested?

- scheduleLoading: Loads a test schedule, and verifies that the page updates with all computed information as well as the schedule itself.

# Checklist
- [x] My code follows ES Lint guidelines
- [x] My solution meets all of the acceptance criteria for the user story
- [x] My code contains necessary comments and documentation
- [x] I have added tests that are useful and cover the new changes
- [x] New and existing unit tests pass locally

### CODE REVIEW

**Comment by ruudkas** [comment]
For the most part everything looks good, I don't see any functional issues.
Minor Requests:
- When the user is logged in and there are no saved schedules we should display some sort of message on that page so it's not just empty. 
- Can the logout button not be button shaped? Thinking maybe just the text instead of the button? 
- I don't know if this would actually work, but could we potentially put the logout button below the profile picture? (This may not actually be plausible space wise)

Note for other reviewers:
If you save an edited schedule with the same name it overwrites (same name will be default option). If you save an edited schedule under a new name it will have "save a copy" behavior.

**Comment by ruudkas** [comment]
Can we potentially get more testing? I see pretty low code coverage for some of the new things added, for example, the account page and the delete and user apis.

**Review by Raffeln6264 — APPROVED** [review]
LGTM, I agree with Kassidy that we should have some kind of message saying "No Saved Schedules" or something like that if there aren't any saved though.

**Comment by ChrisVasterling** [comment]
As per the acceptance criteria for the user story, I think we need to have a "Create Schedule" button on the account page (it should probably just route the user to the input page again). 

I also agree with Kassidy & Nick that we should display a message when there are no schedules in the list.

**Review by ChrisVasterling — APPROVED** [review]
lgtm

**Pull request merged**
