### PR TITLE
Add undo/redo button

### PR DESCRIPTION
**Pull request by ruudkas**
# Jira Ticket

[AR-193](https://academic-cs458.atlassian.net/jira/software/projects/AR/boards/1?selectedIssue=AR-193)

# Description of Changes
_Please describe what this pull request should accomplish_
This PR adds an undo and a redo button to the action bar that allows the user to undo or redo a course move. If after several undos the user drags a course the redo button will no longer be able to redo and actions that were undone.
# Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Feature Update

# How has this been tested?
_Please describe the tests that you used to verify your changes._

**Automated Tests (Preferred)**
- [x] Undo/Redo a course movement from fall to winter

# Checklist
- [x] My code follows ES Lint guidelines
- [x] My solution meets all of the acceptance criteria for the user story
- [x] My code contains necessary comments and documentation
- [x] I have added tests that are useful and cover the new changes
- [x] New and existing unit tests pass locally

### CODE REVIEW

**Review by Raffeln6264 — APPROVED** [review]
Looks good to me, other then the Merge conflicts because of Chris's recent merge, obviously lol.
I did notice a weird bug though that I couldn't replicate that only allowed be to undo a certain number of times (like 2 when I should be able to do more) that was caused after I left the app running for a while on the scheduler page with like 6 courses. But I wasn't able to reproduce it so maybe it was just a one time thing.

**Comment by ChrisVasterling** [comment]
I've got a few comments

These icons should be aligned vertically: 
image

1. I would like some kind of visual indication when an undo/redo are possible
2. When I load a four year plan and drag a course off the schedule, I can't undo that action
3. Load a four year plan, move a course to another semester, move it off the schedule and back to the course list, click undo. I expect the course to move to the other semester, but it goes back to the first. 

I also agree with Nick that there appears to be some bugs that are difficult to reproduce such not being able to undo all the way back.

**Comment by Raffeln6264** [comment]
> I've got a few comments
> 
> These icons should be aligned vertically: image
> 
> 1. I would like some kind of visual indication when an undo/redo are possible
> 2. When I load a four year plan and drag a course off the schedule, I can't undo that action
> 3. Load a four year plan, move a course to another semester, move it off the schedule and back to the course list, click undo. I expect the course to move to the other semester, but it goes back to the first.
> 
> I also agree with Nick that there appears to be some bugs that are difficult to reproduce such not being able to undo all the way back.

@ChrisVasterling and @ruudkas for the Icons not being centered I think that has to do with the aspect ratio of the screen, I noticed depending on my sizing they where either vertically aligned or horizontally aligned, though what you have shown is a little different

**Comment by ChrisVasterling** [comment]
> > I've got a few comments
> > These icons should be aligned vertically: image
> > 
> > 1. I would like some kind of visual indication when an undo/redo are possible
> > 2. When I load a four year plan and drag a course off the schedule, I can't undo that action
> > 3. Load a four year plan, move a course to another semester, move it off the schedule and back to the course list, click undo. I expect the course to move to the other semester, but it goes back to the first.
> > 
> > I also agree with Nick that there appears to be some bugs that are difficult to reproduce such not being able to undo all the way back.
> 
> @ChrisVasterling and @ruudkas for the Icons not being centered I think that has to do with the aspect ratio of the screen, I noticed depending on my sizing they where either vertically aligned or horizontally aligned, though what you have shown is a little different

It has to do with how much horizontal space is available. If you look in dev tools, mine and Kassidy's changes are buttons whereas Nick's is a div (so it breaks to a new line). 
image
Adding breaks after each component would seem to work
image

**Review by ChrisVasterling — APPROVED** [review]
Lgtm, the bugs appear to be fixed

**Pull request merged**
