### PR TITLE
AR-190 Error Bell Notification

### PR DESCRIPTION
**Pull request by ChrisVasterling**
# Jira Ticket

[AR-190](https://academic-cs458.atlassian.net/jira/software/projects/AR/boards/1/backlog?selectedIssue=AR-190)

When running the tests locally, I am occasionally running into a test timeout problem for 1-2 tests. I didn't want to increase the timeout as I believe Matthew may have made those changes already. 

# Description of Changes
A notification icon is displayed in the action bar so that the user can see all active errors and warnings. 
Fix a bug with course filtering

# Type of Change

- [X] Bug Fix
- [X] New Feature
- [ ] Feature Update

# How has this been tested?
Automated testing for opening/closing the popover, badge number, and all errors being displayed. 

**Manual Tests**
N/A

# Checklist
- [X] My code follows ES Lint guidelines
- [X] My solution meets all of the acceptance criteria for the user story
- [X] My code contains necessary comments and documentation
- [X] I have added tests that are useful and cover the new changes
- [x] New and existing unit tests pass locally

### CODE REVIEW

**Comment by ruudkas** [comment]
I have a few comments, I'm not sure how many we actually want to take the time to address.

1. This one's a nitpick but the circle with the number of notifications seems a bit large compared to the size of the bell.
2. The errors in the list don't necessarily appear in the order that they were created, it would be nice if they were in order but this seems like it is potentially more work than it is worth. They look like they appear in order of duplicate course, fall vs spring, then ordered by semester for prereqs.
3. It would be nice if the list differentiated between warnings and errors so the user knew which ones were important to address and which ones are just warnings.

**Review by ruudkas — APPROVED** [review]
LGTM, I had a few comments, but none of them are a big deal that affect the performance.

**Comment by Raffeln6264** [comment]
Looks good to me,  I don't have any major complaints only thing is I kind of agree with Kassidy's 3rd point, could differentiate with like a warning sign (warning triangle) vs a error sign (!), but that is not required in this story.

**Review by Raffeln6264 — APPROVED** [review]
LGTM see above comment

**Pull request merged**
